/**
 * PairMaker
 * Copyright (c) 2025 Dragon & PairMaker Studio. All Rights Reserved.
 * 未經授權，禁止複製、修改或散布本程式碼。
 */

/**
 * Release Note 自動生成器
 * 從 git log 解析 conventional commits 並輸出 Markdown
 *
 * 使用：npx ts-node scripts/release-note.ts [from-tag] [to-tag]
 * 輸出：stdout（可重導向到 release-notes.md）
 */
import { execSync } from 'child_process';

// ── 取得 git log ──────────────────────────────────────────────────────────────

function getGitLog(from?: string, to = 'HEAD'): string {
  const range = from ? `${from}..${to}` : to;
  try {
    return execSync(
      `git log ${range} --pretty=format:"%H|%s|%an|%ad" --date=short --no-merges`,
      { encoding: 'utf-8' },
    );
  } catch {
    return '';
  }
}

function getCurrentTag(): string {
  try {
    return execSync('git describe --tags --abbrev=0', { encoding: 'utf-8' }).trim();
  } catch {
    return 'v0.0.0';
  }
}

function getPreviousTag(currentTag: string): string | undefined {
  try {
    const tags = execSync('git tag --sort=-version:refname', { encoding: 'utf-8' })
      .trim().split('\n');
    const idx = tags.indexOf(currentTag);
    return idx >= 0 && idx + 1 < tags.length ? tags[idx + 1] : undefined;
  } catch {
    return undefined;
  }
}

// ── 解析 Commits ──────────────────────────────────────────────────────────────

interface ParsedCommit {
  hash:   string;
  type:   string;
  scope:  string;
  desc:   string;
  author: string;
  date:   string;
  breaking: boolean;
}

function parseCommit(line: string): ParsedCommit | null {
  const parts = line.split('|');
  if (parts.length < 4) return null;
  const [hash, subject, author, date] = parts;

  // Conventional Commit 格式：type(scope)!: description
  const match = subject.match(/^(\w+)(?:\(([^)]+)\))?(!)?:\s*(.+)$/);
  if (!match) {
    return { hash, type: 'other', scope: '', desc: subject, author, date, breaking: false };
  }

  return {
    hash:    hash.substring(0, 7),
    type:    match[1],
    scope:   match[2] ?? '',
    desc:    match[4],
    author,
    date,
    breaking: !!match[3],
  };
}

// ── 分組 ──────────────────────────────────────────────────────────────────────

const TYPE_LABELS: Record<string, string> = {
  feat:     '✨ 新功能',
  fix:      '🐛 Bug 修復',
  perf:     '⚡ 效能改善',
  refactor: '♻️ 重構',
  test:     '🧪 測試',
  docs:     '📚 文件',
  ci:       '🔧 CI/CD',
  chore:    '🔩 其他維護',
  style:    '💅 樣式調整',
  build:    '📦 建置系統',
  other:    '📝 其他',
};

const DISPLAYED_TYPES = ['feat', 'fix', 'perf', 'refactor'];

function groupCommits(commits: ParsedCommit[]): Map<string, ParsedCommit[]> {
  const groups = new Map<string, ParsedCommit[]>();
  for (const c of commits) {
    const key = DISPLAYED_TYPES.includes(c.type) ? c.type : 'other';
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(c);
  }
  return groups;
}

// ── 生成 Markdown ─────────────────────────────────────────────────────────────

function generateMarkdown(
  tag:     string,
  groups:  Map<string, ParsedCommit[]>,
  breaking: ParsedCommit[],
): string {
  const date  = new Date().toISOString().substring(0, 10);
  const lines: string[] = [];

  lines.push(`# ${tag} (${date})`);
  lines.push('');

  if (breaking.length > 0) {
    lines.push('## ⚠️ Breaking Changes');
    for (const c of breaking) {
      lines.push(`- **${c.scope || c.type}**: ${c.desc} (\`${c.hash}\`)`);
    }
    lines.push('');
  }

  const order = ['feat', 'fix', 'perf', 'refactor', 'other'];
  for (const type of order) {
    const commits = groups.get(type);
    if (!commits?.length) continue;

    lines.push(`## ${TYPE_LABELS[type] ?? type}`);
    for (const c of commits) {
      const scope = c.scope ? `**${c.scope}**: ` : '';
      lines.push(`- ${scope}${c.desc} (\`${c.hash}\`)`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by PairMaker release-note.ts*`);

  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
  const argFrom  = process.argv[2];
  const argTo    = process.argv[3];
  const currentTag = argTo ?? getCurrentTag();
  const prevTag    = argFrom ?? getPreviousTag(currentTag);

  const raw = getGitLog(prevTag, currentTag === 'HEAD' ? undefined : currentTag);
  if (!raw.trim()) {
    console.log(`# ${currentTag}\n\nNo changes.`);
    return;
  }

  const commits  = raw.trim().split('\n').map(parseCommit).filter(Boolean) as ParsedCommit[];
  const breaking = commits.filter(c => c.breaking);
  const groups   = groupCommits(commits);

  const markdown = generateMarkdown(currentTag, groups, breaking);
  process.stdout.write(markdown);
}

main();
